### ISSUE TITLE
Hello, I have encountered some issues

### ISSUE THREAD

**Issue by cloud-jie** [DoTTak/frida-snippets#1]
![image](https://github.com/DoTTak/frida-finance-analysis-snippets/assets/63632785/66ac9593-2410-4f04-8346-74ab3e425661)

**Comment by DoTTak** [comment]
The script you ran was [android_terminate.js](https://github.com/DoTTak/frida-finance-analysis-snippets/blob/7b6388aaf864dc1178b181cd4e1285a2737ec97a/utils/android_terminate.js#L11-L14), but there was a mistake in the `killProcess` and `exit` hooking code. I've corrected it and committed([commit  a5dc464](https://github.com/DoTTak/frida-finance-analysis-snippets/commit/a5dc464b4004b27db2fcaa1fad411204771ae32f)) it again, so please check it out.
